trying something else

diff --git a/.github/workflows/backend-test.yml b/.github/workflows/backend-test.yml
--- a/.github/workflows/backend-test.yml
+++ b/.github/workflows/backend-test.yml
@@ -10,14 +10,14 @@ on:
   pull_request:
     branches: [ main ]
 
-env: 
-  PORT: 5000
-  NODE_ENV: development
-  DEV_URI: mongodb+srv://pourdecisions:ecse428@pourdecisions-cluster.bs25h.mongodb.net/test?retryWrites=true&w=majority
-  DEV_API_HOST: http://localhost
-  DEV_API_PORT: 5000
-  DEV_CLIENT_HOST: http://localhost
-  DEV_CLIENT_PORT: 3000 
+# env: 
+  # PORT: 5000
+  # NODE_ENV: development
+  # DEV_URI: mongodb+srv://pourdecisions:ecse428@pourdecisions-cluster.bs25h.mongodb.net/test?retryWrites=true&w=majority
+  # DEV_API_HOST: http://localhost
+  # DEV_API_PORT: 5000
+  # DEV_CLIENT_HOST: http://localhost
+  # DEV_CLIENT_PORT: 3000 
     
 defaults:
   run:
@@ -36,14 +36,14 @@ jobs:
     steps:
     - uses: actions/checkout@v2
 
-    - name: Log into Docker
-      uses: docker/login-action@v1
-      with:
-        username: pourdecisionsapp
-        password: ECSE428-w2022
+    # - name: Log into Docker
+    #   uses: docker/login-action@v1
+    #   with:
+    #     username: pourdecisionsapp
+    #     password: ECSE428-w2022
 
-    - name: Start containers
-      run: docker-compose -f "../docker-compose.yml" up -d --build
+    # - name: Start containers
+    #   run: docker-compose -f "../docker-compose.yml" up -d --build
 
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v2
@@ -51,13 +51,19 @@ jobs:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
 
-    - name: Install dependencies 
-      run: npm ci
+    # - name: Install dependencies 
+    #   run: npm ci
 
-    - name: Run Cucumber tests and Check coverage
-      run: |
-        npm test | tail -3 | if [[ $(grep -E 'undefined|failed|skipped') ]]; then exit 1; else echo "all tests passed!"; fi;  
+    - name: Build Docker
+      run: docker-compose -f 'docker-compose.test.yml' -p pour-decisions-api-testing up -d 
 
-    - name: Stop containers 
-      if: always() 
-      run: docker-compose -f "../docker-compose.yml" down
+    # - name: Run Cucumber tests and Check coverage
+    #   run: |
+    #     npm test | tail -3 | if [[ $(grep -E 'undefined|failed|skipped') ]]; then exit 1; else echo "all tests passed!"; fi;  
+
+    - name: Run test
+      run: docker-compose -f 'docker-compose.test.yml' -p pour-decisions-api-testing up --build --exit-code-from api-test
+
+    # - name: Stop containers 
+    #   if: always() 
+    #   run: docker-compose -f "../docker-compose.yml" down
